# Generated by Django 5.1.4 on 2024-12-25 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('istifadeciler', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
