# Generated by Django 5.1.2 on 2025-02-03 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('istifadeciler', '0002_delete_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(blank=True, max_length=50, null=True)),
                ('soyad', models.CharField(blank=True, max_length=50, null=True)),
                ('telefon', models.CharField(blank=True, max_length=20, null=True)),
                ('unvan', models.TextField(blank=True, null=True)),
                ('sekil', models.ImageField(default='profile_pics/default.png', upload_to='profile_pics/')),
                ('is_approved', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
