# Generated by Django 5.1.4 on 2024-12-22 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kateqoriya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mehsul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=255)),
                ('brend_kod', models.CharField(max_length=50, unique=True)),
                ('oem_kod', models.CharField(max_length=50, unique=True)),
                ('stok', models.IntegerField()),
                ('brend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mehsullar.brend')),
                ('kateqoriya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mehsullar.kateqoriya')),
                ('marka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mehsullar.marka')),
            ],
        ),
    ]
