# Generated by Django 5.1.4 on 2024-12-23 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0008_alter_sifaris_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sifaris',
            name='user',
        ),
    ]
