# Generated by Django 5.1.4 on 2024-12-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0010_sifaris_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sifaris',
            name='status',
            field=models.CharField(choices=[('gozleyir', 'Gözləyir'), ('hazirlanir', 'Hazırlanır'), ('yoldadir', 'Yoldadır'), ('catdirildi', 'Çatdırıldı')], default='gozleyir', max_length=50),
        ),
    ]
