# Generated by Django 5.1.4 on 2024-12-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0012_remove_sifaris_cemi_mebleg'),
    ]

    operations = [
        migrations.AddField(
            model_name='sifaris',
            name='cemi_mebleg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
