# Generated by Django 5.1.4 on 2024-12-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0014_alter_sifaris_cemi_mebleg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sifaris',
            name='cemi_mebleg',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
