# Generated by Django 5.1.4 on 2024-12-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0015_alter_sifaris_cemi_mebleg'),
    ]

    operations = [
        migrations.AddField(
            model_name='sifaris',
            name='odenilen_mebleg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
