# Generated by Django 5.1.5 on 2025-01-16 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0016_sifaris_odenilen_mebleg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mehsul',
            name='oem_kod',
        ),
        migrations.AddField(
            model_name='mehsul',
            name='oem',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MusteriReyi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rey', models.TextField()),
                ('qiymetlendirme', models.IntegerField(choices=[(1, '1 Ulduz'), (2, '2 Ulduz'), (3, '3 Ulduz'), (4, '4 Ulduz'), (5, '5 Ulduz')], null=True)),
                ('tarix', models.DateTimeField(auto_now_add=True)),
                ('tesdiq', models.BooleanField(default=False)),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Müştəri Rəyi',
                'verbose_name_plural': 'Müştəri Rəyləri',
                'ordering': ['-tarix'],
            },
        ),
        migrations.CreateModel(
            name='OEMKod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=100)),
                ('mehsul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oem_kodlar', to='mehsullar.mehsul')),
            ],
            options={
                'verbose_name': 'OEM Kod',
                'verbose_name_plural': 'OEM Kodlar',
            },
        ),
        migrations.CreateModel(
            name='SebetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdar', models.IntegerField(default=1)),
                ('yaradilma_tarixi', models.DateTimeField(auto_now_add=True)),
                ('mehsul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mehsullar.mehsul')),
            ],
            options={
                'verbose_name': 'Səbət elementi',
                'verbose_name_plural': 'Səbət elementləri',
            },
        ),
    ]
