# Generated by Django 5.1.5 on 2025-01-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0017_remove_mehsul_oem_kod_mehsul_oem_musterireyi_oemkod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brend',
            name='haqqinda',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brend',
            name='sekil',
            field=models.ImageField(blank=True, null=True, upload_to='brend_sekilleri/'),
        ),
        migrations.AddField(
            model_name='mehsul',
            name='haqqinda',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mehsul',
            name='sekil',
            field=models.ImageField(blank=True, null=True, upload_to='mehsul_sekilleri/'),
        ),
    ]
