# Generated by Django 5.1.2 on 2025-02-03 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0018_brend_haqqinda_brend_sekil_mehsul_haqqinda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brend',
            name='sekilyazi',
            field=models.ImageField(blank=True, null=True, upload_to='brend_yazilari/'),
        ),
        migrations.CreateModel(
            name='MarkaSekil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sekil', models.ImageField(blank=True, null=True, upload_to='marka_sekilleri/')),
                ('marka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sekiller', to='mehsullar.marka')),
            ],
        ),
    ]
