# Generated by Django 5.1.2 on 2025-03-09 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehsullar', '0019_brend_sekilyazi_markasekil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avtomodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Avtomobil Modelleri',
                'verbose_name_plural': 'Avtomobil Modelleri',
            },
        ),
        migrations.CreateModel(
            name='AxtarisSozleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=100, unique=True)),
                ('sozler', models.TextField(help_text="Axtarış sözlərini boşluqla ayırın. Məsələn: 'sirga sirgalar'")),
            ],
            options={
                'verbose_name': 'Axtarış Sözləri',
                'verbose_name_plural': 'Axtarış Sözləri',
            },
        ),
        migrations.CreateModel(
            name='Il',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('il', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Avtomobil İlləri',
                'verbose_name_plural': 'Avtomobil İlləri',
            },
        ),
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motor', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Avtomobil Motorları',
                'verbose_name_plural': 'Avtomobil Motorları',
            },
        ),
        migrations.CreateModel(
            name='Yanacaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yanacaq', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Yanacaq',
                'verbose_name_plural': 'Yanacaq',
            },
        ),
        migrations.AlterModelOptions(
            name='brend',
            options={'verbose_name': 'Firmalar', 'verbose_name_plural': 'Firmalar'},
        ),
        migrations.AlterModelOptions(
            name='kateqoriya',
            options={'verbose_name': 'Kateqoriyalar', 'verbose_name_plural': 'Kateqoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='marka',
            options={'verbose_name': 'Markalar', 'verbose_name_plural': 'Markalar'},
        ),
        migrations.AlterModelOptions(
            name='mehsul',
            options={'verbose_name': 'Məhsullar', 'verbose_name_plural': 'Məhsullar'},
        ),
        migrations.AlterModelOptions(
            name='sebet',
            options={'verbose_name': 'Səbət', 'verbose_name_plural': 'Səbət'},
        ),
        migrations.AlterModelOptions(
            name='sifaris',
            options={'verbose_name': 'Sifarişlər', 'verbose_name_plural': 'Sifarişlər'},
        ),
        migrations.AlterModelOptions(
            name='sifarismehsul',
            options={'verbose_name': 'Sifariş Məhsulları', 'verbose_name_plural': 'Sifariş Məhsulları'},
        ),
        migrations.AddField(
            model_name='mehsul',
            name='yenidir',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='mehsul',
            name='sekil',
            field=models.ImageField(blank=True, default='mehsul_sekilleri/noimage.webp', null=True, upload_to='mehsul_sekilleri/'),
        ),
        migrations.AlterField(
            model_name='oemkod',
            name='kod',
            field=models.TextField(help_text='OEM kodlarını boşluqla ayırın. Hər bir kod avtomatik olaraq ayrı-ayrı saxlanılacaq.'),
        ),
        migrations.AddField(
            model_name='mehsul',
            name='axtaris_sozleri',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mehsullar', to='mehsullar.axtarissozleri'),
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avtomobil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mehsullar.marka')),
                ('il', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mehsullar.il')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mehsullar.avtomodel')),
                ('motor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mehsullar.motor')),
                ('yanacaq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mehsullar.yanacaq')),
            ],
            options={
                'verbose_name': 'Modeller',
                'verbose_name_plural': 'Modeller',
            },
        ),
        migrations.AddField(
            model_name='mehsul',
            name='model',
            field=models.ManyToManyField(blank=True, to='mehsullar.model'),
        ),
    ]
