# Generated by Django 5.1.2 on 2025-03-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sekil', models.ImageField(upload_to='hero_slides/', verbose_name='Şəkil')),
                ('basliq', models.CharField(max_length=200, verbose_name='Başlıq')),
                ('alt_basliq', models.CharField(max_length=300, verbose_name='Alt Başlıq')),
                ('yaradilma_tarixi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['-yaradilma_tarixi'],
            },
        ),
    ]
