# Generated by Django 5.1.2 on 2025-02-03 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Maşının Adı')),
                ('car_year', models.CharField(max_length=100, verbose_name='Buraxılma Tarixi')),
                ('engine_capacity', models.FloatField(verbose_name='Motor Həcmi')),
                ('car_type', models.CharField(choices=[('rent', 'İcarə'), ('sale', 'Satış')], max_length=4, verbose_name='İcarə/Satış')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Satış Qiyməti')),
                ('rent_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='İcarə Qiyməti')),
                ('description', models.TextField(verbose_name='Haqqında')),
            ],
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/', verbose_name='Maşının Şəkli')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rentacar.car')),
            ],
        ),
    ]
