# Generated by Django 5.1.2 on 2025-03-09 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Avtomobillər', 'verbose_name_plural': 'Avtomobillər'},
        ),
        migrations.AlterModelOptions(
            name='carimage',
            options={'verbose_name': 'Avtomobil Şəkilləri', 'verbose_name_plural': 'Avtomobil Şəkilləri'},
        ),
    ]
